"use strict";
const clone = x => JSON.parse(JSON.stringify(x));
function date(value) {
  const s=String(value||'');
  if(!/^\d{4}-\d{2}-\d{2}$/.test(s)||!Number.isFinite(Date.parse(s+'T00:00:00Z'))||new Date(s+'T00:00:00Z').toISOString().slice(0,10)!==s) throw Error('日期请填写真实的 YYYY-MM-DD。');
  return s;
}
function shift(d,n){return new Date(Date.parse(date(d)+'T00:00:00Z')+n*86400000).toISOString().slice(0,10);}
function days(a,b){return Math.round((Date.parse(date(b)+'T00:00:00Z')-Date.parse(date(a)+'T00:00:00Z'))/86400000);}
function hasIntl(){return typeof Intl!=='undefined'&&typeof Intl.DateTimeFormat==='function';}
function zone(z){try{if(typeof z!=='string'||!z)throw Error('empty zone');if(hasIntl())new Intl.DateTimeFormat('en',{timeZone:z}).format(new Date());else if(typeof Java!=='undefined')Java.type('java.time.ZoneId').of(z);else throw Error('missing date runtime');return z;}catch(_){throw Error('时区无效或运行时缺少日期支持，例如 Asia/Taipei。');}}
function localDay(iso,z){const t=new Date(iso);if(!Number.isFinite(t.getTime()))throw Error('时间无效。');zone(z);if(hasIntl()){const p=new Intl.DateTimeFormat('en-US',{timeZone:z,year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(t);return ['year','month','day'].map(k=>p.find(x=>x.type===k).value).join('-');}const zoneId=Java.type('java.time.ZoneId').of(z);return String(Java.type('java.time.Instant').ofEpochMilli(t.getTime()).atZone(zoneId).toLocalDate().toString());}
function text(x,max=4000){const v=String(x??'').trim();if(v.length>max)throw Error('内容超过 '+max+' 字符，请分条保存。');return v;}
function number(x,min,max){if(x===''||x===null||typeof x==='boolean')throw Error('请填写数字。');const n=Number(x);if(!Number.isFinite(n)||n<min||n>max)throw Error('数值超出可记录范围。');return n;}
function empty(){return {schema:2,revision:0,settings:{name:'Reiko',timeZone:'Asia/Taipei',holidaySet:'none',countdownDays:30},chatBinding:{chatId:'',chatTitle:'',characterCardId:'',characterName:''},dailyRecords:{},events:[],weights:[],cycles:[],digestCache:{},digestDeliveries:{},requests:[]};}
function validate(s){
 if(!s||s.schema!==2||!Number.isInteger(s.revision)||s.revision<0||!s.settings||!s.dailyRecords||Array.isArray(s.dailyRecords)||!Array.isArray(s.events)||!Array.isArray(s.weights)||!Array.isArray(s.cycles)||!s.digestCache||Array.isArray(s.digestCache)||!Array.isArray(s.requests))throw Error('数据结构不完整，未覆盖原文件。');
 zone(s.settings.timeZone);number(s.settings.countdownDays,1,365);if(!['none','basic'].includes(s.settings.holidaySet))throw Error('节日设置无效。');
 if(!s.chatBinding||typeof s.chatBinding!=='object')s.chatBinding={chatId:'',chatTitle:'',characterCardId:'',characterName:''};
 for(const k of ['chatId','chatTitle','characterCardId','characterName'])if(typeof s.chatBinding[k]!=='string')throw Error('对话绑定格式无效。');
 const ids=new Set();const entry=x=>{if(!x||typeof x.id!=='string'||!x.id||ids.has(x.id))throw Error('记录标识缺失或重复。');ids.add(x.id);};
 for(const [d,r] of Object.entries(s.dailyRecords)){date(d);if(!r||!Array.isArray(r.notes))throw Error('每日碎片格式无效。');if(r.sleepHours!=null)number(r.sleepHours,0,48);for(const n of r.notes){entry(n);if(typeof n.text!=='string'||!n.text.trim())throw Error('碎片内容无效。');}}
 for(const e of s.events){entry(e);date(e.date);if(typeof e.title!=='string'||!e.title.trim())throw Error('事件标题无效。');}
 for(const w of s.weights){entry(w);date(w.date);number(w.value,0.01,1000);if(!Number.isFinite(Date.parse(w.recordedAt)))throw Error('体重时间无效。');}
 for(const c of s.cycles){entry(c);date(c.startDate);if(c.confirmedDates!==undefined){if(!Array.isArray(c.confirmedDates))throw Error('经期确认格式无效。');for(const d of c.confirmedDates){date(d);if(d<c.startDate||c.endDate&&d>c.endDate)throw Error('经期确认日期不一致。');}}if(c.endedOn){date(c.endedOn);if(c.endedOn!==c.endDate)throw Error('经期结束状态不一致。');}if(c.endDate){date(c.endDate);if(c.endDate<c.startDate)throw Error('经期日期不一致。');}}
 if(!s.digestDeliveries||typeof s.digestDeliveries!=='object'||Array.isArray(s.digestDeliveries))s.digestDeliveries={};
 for(const [d,r] of Object.entries(s.digestCache)){date(d);if(!r||typeof r.text!=='string')throw Error('交接缓存无效。');}
 for(const [d,r] of Object.entries(s.digestDeliveries)){date(d);if(!r||typeof r!=='object'||typeof r.chatId!=='string'||typeof r.deliveredAt!=='string')throw Error('交接投递记录无效。');}return s;
}
function periodDay(s,d){
 const c=s.cycles.filter(c=>c.startDate<=d).sort((a,b)=>b.startDate.localeCompare(a.startDate))[0];
 if(!c)return null;
 if(c.endedOn===d)return {cycleId:c.id,startDate:c.startDate,ended:true,confirmed:true};
 if(c.endedOn&&d>=c.endedOn||c.endDate&&d>c.endDate)return null;
 const confirmed=d===c.startDate||!!c.endDate&&!c.endedOn||(c.confirmedDates||[]).includes(d);
 return {cycleId:c.id,startDate:c.startDate,dayNumber:days(c.startDate,d)+1,confirmed,pending:!confirmed,active:true};
}
function cycleStatus(s,d){const items=s.cycles.filter(x=>x.startDate<=d).slice().sort((a,b)=>a.startDate.localeCompare(b.startDate));const last=items[items.length-1];const base={period:periodDay(s,d),prediction:false,records:clone(s.cycles),lastPeriodStart:last?.startDate||null,lastPeriodEnd:last?.endDate||null};if(items.length<3)return {...base,reason:'至少记录三次开始日期后再估算。'};const gaps=items.slice(-7).slice(1).map((x,i)=>days(items.slice(-7)[i].startDate,x.startDate));const avg=Math.round(gaps.reduce((a,b)=>a+b,0)/gaps.length);if(gaps.some(n=>n<15||n>60)||Math.max(...gaps)-Math.min(...gaps)>14)return {...base,reason:'已记录的间隔差异较大，暂不推算。'};const predicted=shift(last.startDate,avg);return {...base,prediction:true,estimated:true,averageCycleDays:avg,predictedNextStart:predicted,predictedDaysRemaining:days(d,predicted),method:'最近最多六个间隔的算术平均，仅作日期参考。'};}
function holidays(d,set){if(set!=='basic')return [];const names={'01-01':'元旦','02-14':'情人节','03-08':'国际妇女节','05-01':'劳动节','06-01':'儿童节','10-31':'万圣夜','12-25':'圣诞节'};return names[d.slice(5)]?[{date:d,title:names[d.slice(5)],kind:'observance',note:'公历纪念日，不代表当地放假安排。'}]:[];}
function daily(s,d){return {date:d,period:periodDay(s,d),...clone(s.dailyRecords[d]||{}),notes:clone(s.dailyRecords[d]?.notes||[]),weights:clone(s.weights.filter(w=>w.date===d).sort((a,b)=>Date.parse(a.recordedAt)-Date.parse(b.recordedAt)))};}
function digestData(s,d){const y=shift(d,-1);const events=s.events.filter(e=>!e.cancelled);return {date:d,timeZone:s.settings.timeZone,name:s.settings.name||'你',yesterday:{...daily(s,y),events:clone(events.filter(e=>e.date===y))},today:{...daily(s,d),events:clone(events.filter(e=>e.date===d)),holidays:holidays(d,s.settings.holidaySet)},upcoming:clone(events.filter(e=>e.countdown&&e.date>d&&days(d,e.date)<=s.settings.countdownDays).sort((a,b)=>a.date.localeCompare(b.date)).map(e=>({...e,daysRemaining:days(d,e.date)}))),anniversaries:clone(events.filter(e=>e.kind==='anniversary'&&e.date<d).map(e=>({...e,daysElapsed:days(e.date,d)}))),cycle:cycleStatus(s,d)};}
function renderDigest(x){const y=x.yesterday,t=x.today,bits=[];const brief=v=>v.length>140?v.slice(0,140)+'…（节选）':v;const sourceName=n=>n.createdBy==='assistant'?(n.createdByName||'模型'):'你';const noteLimit=3,eventLimit=4;if(y.weights.length)bits.push(x.name+'昨天记录的体重是'+y.weights[y.weights.length-1].value+' kg');if(y.sleepHours!=null)bits.push('睡眠记录为'+y.sleepHours+'小时');if(y.mood)bits.push('留下的状态是“'+brief(y.mood)+'”');if(y.activity)bits.push('记下做过的事：'+brief(y.activity));for(const n of y.notes.slice(-noteLimit))bits.push(sourceName(n)+'留下的碎片：“'+brief(n.text)+'”');for(const e of y.events.slice(0,eventLimit))bits.push('昨天'+(e.completed?'已完成':'安排过')+'“'+e.title+'”');
 const current=[];if(y.notes.length>noteLimit)bits.push('还有'+(y.notes.length-noteLimit)+'条碎片留在原记录里');for(const h of t.holidays)current.push('今天是'+h.title);for(const e of t.events.slice(0,eventLimit))current.push('今天'+(e.time?e.time+' ':'')+'有“'+e.title+'”'+(e.completed?'，已标记完成':''));if(t.mood)current.push('今天已记录的状态是“'+brief(t.mood)+'”');if(t.sleepHours!=null)current.push('今天已记下'+t.sleepHours+'小时睡眠');if(t.weights.length)current.push('今天已留下'+t.weights[t.weights.length-1].value+' kg 的体重记录');if(t.activity)current.push('今天已记下：'+brief(t.activity));for(const n of t.notes.slice(-noteLimit))current.push('今天'+sourceName(n)+'又留下：“'+brief(n.text)+'”');if(t.notes.length>noteLimit)current.push('今天另外'+(t.notes.length-noteLimit)+'条碎片仍在海面');for(const e of x.upcoming.slice(0,3))current.push('写着“'+e.title+'”的贝壳，还有'+e.daysRemaining+'天靠岸');const cy=x.cycle;if(cy.lastPeriodStart===y.date)bits.push('昨天记录了经期开始');if(cy.lastPeriodEnd===y.date)bits.push('昨天记录了经期结束');if(cy.period?.ended||cy.lastPeriodEnd===x.date&&!cy.period?.active)current.push('今天记录了经期结束');else if(cy.period?.active)current.push(cy.period.confirmed?'今天是经期第'+cy.period.dayNumber+'天':'从已记录的开始日算起，今天是经期第'+cy.period.dayNumber+'天，今天是否仍在经期还待你确认');if(cy.prediction&&cy.predictedDaysRemaining>=0&&cy.predictedDaysRemaining<=14)current.push(cy.predictedDaysRemaining===0?'按现有记录估算，今天接近预计经期开始日':'按现有记录估算，距离预计经期还有约'+cy.predictedDaysRemaining+'天');
 const first=bits.length?'小水母从昨天的海底回来了。'+bits.join('；')+'。':(current.length?'小水母浮上海面，带来了今天靠近岸边的消息。':'小水母下去转了一圈，空着触手回来了。昨天的海底很安静。');return first+(current.length?'\n\n'+current.join('；')+'。':'');}
function stamp(who,time,old,source={}){const out={createdBy:old?.createdBy||who,createdAt:old?.createdAt||time,updatedBy:who,updatedAt:time};if(!old&&who==='assistant'){if(source.name)out.createdByName=String(source.name);if(source.cardId)out.createdByCardId=String(source.cardId);if(source.chatId)out.createdInChatId=String(source.chatId);}if(who==='assistant'){if(source.name)out.updatedByName=String(source.name);if(source.cardId)out.updatedByCardId=String(source.cardId);if(source.chatId)out.updatedInChatId=String(source.chatId);}return out;}
function actor(p){const a=p.createdBy||p.author||'assistant';if(!['user','assistant'].includes(a))throw Error('记录者只能是 user 或 assistant。');return a;}
function apply(s,action,p={},now=new Date().toISOString(),id=()=>Math.random().toString(36).slice(2)+Date.now().toString(36)){
 const today=localDay(now,s.settings.timeZone),d=date(p.date||today),who=actor(p),source={name:text(p.createdByName||p.updatedByName||'',120),cardId:text(p.createdByCardId||p.updatedByCardId||'',200),chatId:text(p.createdInChatId||p.updatedInChatId||'',200)};let changed=false,result={};const touch=()=>{changed=true;};
 const list=(key)=>s[key];const find=(key)=>{const item=list(key).find(x=>x.id===p.id);if(!item)throw Error('这条记录已不存在，请刷新。');return item;};
 switch(action){
 case 'get_state':result={state:clone(s),today};break;
 case 'get_binding_context':result={binding:clone(s.chatBinding||{chatId:'',chatTitle:'',characterCardId:'',characterName:''}),context:null};break;
 case 'get_daily_summary':result={record:daily(s,d)};break;
 case 'save_daily':{const old=s.dailyRecords[d]||{date:d,notes:[]};const r={...old,...stamp(who,now,old,source)};if('sleepHours'in p)r.sleepHours=p.sleepHours==null||p.sleepHours===''?null:number(p.sleepHours,0,48);for(const k of ['mood','activity'])if(k in p)r[k]=text(p[k],2000)||null;s.dailyRecords[d]=r;touch();result={record:daily(s,d)};break;}
 case 'add_daily_note':{const value=text(p.text);if(!value)throw Error('先留下一句话。');const r=s.dailyRecords[d]||(s.dailyRecords[d]={date:d,notes:[],...stamp(who,now,null,source)});const n={id:id(),date:d,text:value,author:who,...stamp(who,now,null,source)};r.notes.push(n);Object.assign(r,stamp(who,now,r,source));touch();result={note:n};break;}
 case 'update_note':case 'delete_note':{let found;for(const r of Object.values(s.dailyRecords)){const n=r.notes.find(x=>x.id===p.id);if(n){found=n;if(action==='delete_note')r.notes=r.notes.filter(x=>x.id!==p.id);else {const v=text(p.text);if(!v)throw Error('内容不能为空。');Object.assign(n,{text:v},stamp(who,now,n,source));}Object.assign(r,stamp(who,now,r,source));break;}}if(!found)throw Error('碎片不存在。');touch();result={id:p.id};break;}
 case 'add_event':case 'update_event':{const old=action==='update_event'?find('events'):null;const e={...(old||{id:id(),countdown:true,kind:'event',completed:false}),...stamp(who,now,old,source)};for(const k of ['title','note'])if(k in p)e[k]=text(p[k],k==='title'?120:2000);if(!e.title)throw Error('贝壳需要一个名字。');if('date'in p||!old)e.date=date(p.date);if('time'in p){e.time=text(p.time)||null;if(e.time&&!/^([01]\d|2[0-3]):[0-5]\d$/.test(e.time))throw Error('时间请填写 HH:mm。');}if('countdown'in p)e.countdown=p.countdown===true||p.countdown==='true';if('completed'in p)e.completed=p.completed===true||p.completed==='true';if('kind'in p){if(!['event','anniversary','holiday'].includes(p.kind))throw Error('事件类型无效。');e.kind=p.kind;}if(old)Object.assign(old,e);else s.events.push(e);touch();result={event:e};break;}
 case 'save_chat_binding':{const b={chatId:text(p.chatId,200),chatTitle:text(p.chatTitle,200),characterCardId:text(p.characterCardId,200),characterName:text(p.characterName,120)};if(!b.chatId)throw Error('没有取得当前对话，请从目标对话中打开插件。');s.chatBinding=b;touch();result={chatBinding:clone(b)};break;}
 case 'clear_chat_binding':s.chatBinding={chatId:'',chatTitle:'',characterCardId:'',characterName:''};touch();result={chatBinding:clone(s.chatBinding)};break;
 case 'delete_event':find('events');s.events=s.events.filter(x=>x.id!==p.id);touch();result={deletedId:p.id};break;
 case 'get_events':{const from=p.from?date(p.from):null,to=p.to?date(p.to):null;if(from&&to&&from>to)throw Error('日期范围顺序不正确。');result={events:clone(s.events.filter(x=>(!from||x.date>=from)&&(!to||x.date<=to)).sort((a,b)=>a.date.localeCompare(b.date)).map(e=>({...e,daysRemaining:days(d,e.date),daysElapsed:days(e.date,d)})))};break;}
 case 'record_weight':{const ts=p.recordedAt||now;if(!/(Z|[+-]\d{2}:\d{2})$/.test(ts)||!Number.isFinite(Date.parse(ts)))throw Error('记录时间须包含时区。');const w={id:id(),value:number(p.value,0.01,1000),unit:'kg',date:p.date?d:localDay(ts,s.settings.timeZone),recordedAt:ts,...stamp(who,now,null,source)};s.weights.push(w);touch();result={weight:w};break;}
 case 'delete_weight':find('weights');s.weights=s.weights.filter(x=>x.id!==p.id);touch();result={deletedId:p.id};break;
 case 'get_weight_records':{const from=p.from?date(p.from):null,to=p.to?date(p.to):null;if(from&&to&&from>to)throw Error('日期范围顺序不正确。');let ws=s.weights.filter(x=>(!p.date||x.date===d)&&(!from||x.date>=from)&&(!to||x.date<=to)).sort((a,b)=>Date.parse(b.recordedAt)-Date.parse(a.recordedAt));if(p.latest===true||p.latest==='true')ws=ws.slice(0,1);result={weights:clone(ws)};break;}
 case 'record_cycle':{const start=date(p.startDate);if(start>today)throw Error('实际经期不能记录为未来日期。');const old=p.id?find('cycles'):s.cycles.find(x=>x.startDate===start);const end='endDate'in p?(p.endDate?date(p.endDate):null):(old?.endDate||null);if(end&&(end<start||end>today))throw Error('结束日期应在开始日期之后且不晚于今天。');if(s.cycles.some(x=>x!==old&&x.startDate===start))throw Error('已有同一天的开始记录。');if(s.cycles.some(x=>x!==old&&start<=(x.endDate||today)&&(end||today)>=x.startDate))throw Error('经期记录日期重叠，请编辑已有记录。');const c={id:old?.id||id(),startDate:start,endDate:end,confirmedDates:(old?.confirmedDates||[]).filter(d=>d>=start&&(!end||d<=end)),endedOn:old?.endedOn===end?end:null,...stamp(who,now,old,source)};if(old)Object.assign(old,c);else s.cycles.push(c);touch();result={cycle:c,status:cycleStatus(s,d)};break;}
 case 'confirm_cycle_day':{
 if(d>today)throw Error('不能确认未来日期。');
 const c=find('cycles');if(d<c.startDate||c.endDate&&d>c.endDate||c.endedOn&&d>=c.endedOn)throw Error('这一天不在此经期内，请编辑经期记录。');
 if(!['ongoing','ended'].includes(p.status))throw Error('请选择仍在经期或今天已结束。');
 if(p.status==='ongoing'){c.confirmedDates=[...new Set([...(c.confirmedDates||[]),d])].sort();}
 else {if((c.confirmedDates||[]).some(x=>x>d))throw Error('后面还有已确认的经期记录，请先编辑日期。');c.endDate=d;c.endedOn=d;}
 Object.assign(c,stamp(who,now,c,source));touch();result={cycle:c,record:daily(s,d),status:cycleStatus(s,d)};break;}
 case 'delete_cycle':find('cycles');s.cycles=s.cycles.filter(x=>x.id!==p.id);touch();result={deletedId:p.id};break;
 case 'get_cycle_status':result={status:cycleStatus(s,d)};break;
 case 'save_settings':{const v={...s.settings};if('name'in p)v.name=text(p.name,40)||'你';if('timeZone'in p)v.timeZone=zone(text(p.timeZone));if('holidaySet'in p){if(!['none','basic'].includes(p.holidaySet))throw Error('节日设置无效。');v.holidaySet=p.holidaySet;}if('countdownDays'in p)v.countdownDays=Math.round(number(p.countdownDays,1,365));s.settings=v;touch();result={settings:v};break;}
 case 'preview_daily_digest':{const data=digestData(s,d);result={digest:{...data,text:renderDigest(data)},alreadyGenerated:!!s.digestCache[d],preview:true};break;}
 case 'generate_daily_digest':{if(s.digestCache[d])result={digest:clone(s.digestCache[d]),alreadyGenerated:true};else {const data=digestData(s,d);const digest={...data,text:renderDigest(data),generatedAt:now,sourceRevision:s.revision};s.digestCache[d]=digest;touch();result={digest,alreadyGenerated:false};}break;}
 case 'get_digest_delivery':result={delivery:clone(s.digestDeliveries[d]||null)};break;
 case 'mark_digest_delivered':{const chatId=text(p.chatId,200);if(!chatId)throw Error('投递对话不能为空。');s.digestDeliveries[d]={date:d,chatId,deliveredAt:now};touch();result={delivery:clone(s.digestDeliveries[d])};break;}
 default:throw Error('未知操作：'+action);
 }
 if(changed&&['record_cycle','confirm_cycle_day','delete_cycle'].includes(action)&&!s.digestDeliveries[today])delete s.digestCache[today];
 return {changed,result:{success:true,...clone(result)}};
}
module.exports={clone,date,shift,days,zone,localDay,text,empty,validate,periodDay,cycleStatus,holidays,daily,digestData,renderDigest,apply};
