'use strict';
const D=require('./domain');
let queue=Promise.resolve();
const check=r=>{if(!r||r.success===false)throw Error(r?.message||'文件操作未成功。');return r;};
function hash(s){let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619);}return (h>>>0).toString(16);}
function directory(){const root=ToolPkg.getConfigDir('com.reiko.tidal_keeps');if(!root||typeof root!=='string')throw Error('未取得插件数据目录。');return root.replace(/\/$/,'')+'/tidal-v2';}
async function load(){const dir=directory(),good=[],bad=[];for(let slot=0;slot<2;slot++){const path=dir+'/state-'+slot+'.json';const e=check(await Tools.Files.exists(path,'android'));if(e.exists===false)continue;if(e.exists!==true)throw Error('无法确认数据文件状态。');const r=check(await Tools.Files.read({path,environment:'android'}));try{const env=JSON.parse(r.content);if(typeof env.payload!=='string'||hash(env.payload)!==env.checksum)throw Error('校验失败');const s=D.validate(JSON.parse(env.payload));if(!Number.isInteger(s.revision)||s.revision<0)throw Error('版本无效');good.push({s,slot});}catch(e){bad.push(path);}}if(!good.length&&bad.length)throw Error('数据文件无法读取。已保护原文件，请先导出目录中的文件排查。');good.sort((a,b)=>b.s.revision-a.s.revision);return {s:good[0]?.s||D.empty(),slot:good[0]?.slot??1,recovered:bad.length>0,dir};}
async function save(loaded){const {s,dir,slot}=loaded;s.revision++;D.validate(s);check(await Tools.Files.mkdir(dir,true,'android'));const payload=JSON.stringify(s),body=JSON.stringify({checksum:hash(payload),payload}),path=dir+'/state-'+(1-slot)+'.json';check(await Tools.Files.write(path,body,false,'android'));const result=check(await Tools.Files.read({path,environment:'android'}));if(result.content!==body)throw Error('保存后校验未通过，请刷新确认；上一份数据仍保留。');}
function migrate(old,now,settings){if(!old||typeof old!=='object'||!old.dailyRecords||!Array.isArray(old.events)||!Array.isArray(old.weights)||!Array.isArray(old.cycles))throw Error('旧数据格式不正确。');const s=D.empty();if(settings)s.settings=D.clone(settings);const run=(a,p)=>D.apply(s,a,p,now);function audit(item,original){for(const k of ['createdAt','updatedAt'])if(original[k]&&Number.isFinite(Date.parse(original[k])))item[k]=original[k];}
for(const [date,r]of Object.entries(old.dailyRecords)){run('save_daily',{date,sleepHours:r.sleepHours??null,mood:r.mood||'',activity:r.activity||'',createdBy:r.createdBy||'user'});if(!Array.isArray(r.notes))throw Error('旧碎片格式不正确。');for(const n of r.notes){const out=run('add_daily_note',{date,text:n.text,createdBy:n.author||n.createdBy||'user'});audit(s.dailyRecords[date].notes.find(x=>x.id===out.result.note.id),n);}}
for(const e of old.events){const out=run('add_event',{...e,createdBy:e.createdBy||'user'});audit(s.events.find(x=>x.id===out.result.event.id),e);}for(const w of old.weights){const out=run('record_weight',{...w,createdBy:w.createdBy||'user'});audit(s.weights.find(x=>x.id===out.result.weight.id),w);}for(const c of old.cycles){const {id,...p}=c;const out=run('record_cycle',{...p,createdBy:c.createdBy||'user'});audit(s.cycles.find(x=>x.id===out.result.cycle.id),c);}return D.validate(s);}
async function perform(action,params){const l=await load(),p={...params};if(action==='export_data')return {success:true,text:JSON.stringify(l.s,null,2),dataPath:l.dir,recovered:l.recovered};if(action==='import_legacy'){if(Object.keys(l.s.dailyRecords).length||l.s.events.length||l.s.weights.length||l.s.cycles.length)throw Error('只允许向空档案导入旧版数据，避免覆盖现有记录。');const old=check(await Tools.Files.read({path:'/root/tidal_keeps_data/state.json',environment:'linux'}));const migrated=migrate(JSON.parse(old.content),new Date().toISOString(),l.s.settings);migrated.settings=l.s.settings;migrated.revision=l.s.revision;l.s=migrated;await save(l);return {success:true,message:'旧记录已导入，原文件保留。旧版晨报缓存未导入。'};}
const requestId=p.requestId;delete p.requestId;const signature=JSON.stringify([action,p]);if(requestId){if(typeof requestId!=='string'||requestId.length>200)throw Error('请求标识无效。');const old=l.s.requests.find(x=>x.id===requestId);if(old){if(old.signature!==signature)throw Error('同一请求标识对应了不同内容，请刷新后重试。');return {...old.result,replayed:true};}}
const output=D.apply(l.s,action,p);if(output.changed){if(requestId){l.s.requests.push({id:requestId,signature,result:output.result});l.s.requests=l.s.requests.slice(-100);}await save(l);}if(action==='get_state')Object.assign(output.result,{dataPath:l.dir,recovered:l.recovered});if(output.result.digest)output.result.text=output.result.digest.text;return output.result;}
function dispatch(action,p={}){const next=queue.then(()=>perform(action,p));queue=next.catch(()=>{});return next;}
module.exports={dispatch,hash,migrate};
